frontend/models/Reply.php
<?php

namespace app\models;

use common\models\CommonModel;
/**
 * This is the model class for table "pgdx_reply".
 *
 * @property int $id
 * @property string $createTime 发表时间
 * @property string $updateTime
 * @property string $replyContent 内容
 * @property int $courseMainId 主课程ID
 * @property int $courseId 子课程ID
 * @property int $userId 用户ID
 * @property string $replyStatus 0(没有回复)1(有回复)2(已回答)
 * @property string $replyType q:提问 a:回答 r:回复,所有reply只针对大课
 * @property int $refId 如果type是回答,需要指明refId为提问的ID；如果type是回复,需要指明refId为提问/回答/回复的ID
 * @property string $isdel 是否已删除 0:未删除 1:已删除
 */
class Reply extends CommonModel
{
	public $id;
	public $createTime;			// 发表时间
	public $updateTime;
	public $replyContent;		// 内容
	public $courseMainId;		// 主课程ID
	public $courseId;			// 子课程ID
	public $userId;				// 用户ID
	public $replyStatus;			// 0(没有回复)1(有回复)2(已回答)
	public $replyType;			// q:提问 a:回答 r:回复,所有reply只针对大课
	public $refId;				// 如果type是回答,需要指明refId为提问的ID；如果type是回复,需要指明refId为提问/回答/回复的ID
	public $isdel;				// 是否已删除 0:未删除 1:已删除
	
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'pgdx_reply';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['createTime', 'updateTime', 'replyContent', 'userId', 'replyStatus', 'replyType'], 'required'],
            [['createTime', 'updateTime'], 'safe'],
            [['courseMainId', 'courseId', 'userId', 'refId'], 'integer'],
            [['replyContent'], 'string', 'max' => 2048],
            [['replyStatus'], 'string', 'max' => 3],
            [['replyType', 'isdel'], 'string', 'max' => 1],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'createTime' => '发表时间',
            'updateTime' => 'Update Time',
            'replyContent' => '内容',
            'courseMainId' => '主课程ID',
            'courseId' => '子课程ID',
            'replyStatus' => '留言状态',
            'replyType' => 'q:提问 a:回答 r:回复,所有reply只针对大课',
            'refId' => '如果type是回答,需要指明refId为提问的ID；如果type是回复,需要指明refId为提问/回答/回复的ID',
            'isdel' => '是否已删除 0:未删除 1:已删除',
        ];
    }
}

frontend/controllers/ReplyController.php
<?php

namespace frontend\controllers;

use Yii;
use app\models\Reply;
use app\models\ReplySearch;
use app\models\UserSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\data\ArrayDataProvider;
use common\page\Page;
use common\http\RestfulHttp;
use app\models\CourseMainSearch;


/**
 * ReplyController 问答管理.
 */
class ReplyController extends Controller
{
	/**
	 * @inheritdoc
	 */
	public function behaviors()
	{
		return [
				'access' => [
						'class' => AccessControl::className(),
						'rules' => [
								[
										'actions' => [],
										'allow' => true,
										'roles' => ['@'],
								]
						],
				],
				'verbs' => [
						'class' => VerbFilter::className(),
						'actions' => [
								'delete' => ['POST'],
						],
				],
		];
	}
	
	/**
	 * Lists all Reply models.
	 * @return mixed
	 */
	public function actionIndex()
	{
		
		$req_params = Yii::$app->request->queryParams;
		
		$req_params = Yii::$app->request->queryParams;
		
		//分页
		$page = Page::generatePage($req_params);
		$req_params['pgopr'] = 'reply';
		//查询主课程信息
		$courseSearch = new CourseMainSearch();
		$dataProvider = $courseSearch->search($req_params, $page);
		
		$searchModel = new CourseMainSearch();
		$searchModel->load($req_params, 'CourseMainSearch');
		
		return $this->render('index', [
				'searchModel' => $searchModel,
				'dataProvider' => $dataProvider,
				'page' => $page,
		]);
	}
	
	public function actionReplyIndex($courseMainId)
	{
		$req_params = Yii::$app->request->queryParams;
		
		$courseMain = new CourseMainSearch();
		$courseMain = CourseMainSearch::findModel($courseMainId);
		
		$page = Page::generatePage($req_params);
		$req_params['pgopr'] = 'reply';
		$replySearch = new ReplySearch();
		$dataProvider = $replySearch->search($req_params, $page, $courseMainId);
		
		$searchModel = new ReplySearch();
		$searchModel->load($req_params, 'ReplySearch');
		
		$model = new ReplySearch();
		
		return $this->render('reply_index', [
				'searchModel' => $searchModel,
				'courseMain' => $courseMain,
				'model' => $model,
				'dataProvider' => $dataProvider,
				'page' => $page,
		]);
	}
	
	public function actionCreate($questoinId,$courseMainId)
	{
		$model = new ReplySearch(); // your model can be loaded here
		
		// Check if there is an Editable ajax request
		if (isset($_POST['hasEditable'])) {
			// use Yii's response format to encode output as JSON
			\Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
			
			// read your posted model attributes
			if ($model->load($_POST)) {
				// read or convert your posted information
				$value = $model->replyContent;
				$model->userId = 137;
				$model->courseMainId = $courseMainId;
				if (trim($value) == '') {
					return ['output' => $value, 'message' => '不能为空'];
				} else if (mb_strlen(trim($value)) > 1024) {
					return ['output' => $value, 'message' => '不能超过1024个字符'];
				}
				if ($model->save($questoinId)) {
					// return JSON encoded output in the below format
					return ['output' => $value, 'message' => '', 'id' => $questoinId, 'updateTime' => date('Y-m-d H:i:s', time())];
				} else {
					return ['output' => $value, 'message' => '回复失败'];
				}
				// alternatively you can return a validation error
				// return ['output'=>'', 'message'=>'Validation error'];
			} // else if nothing to do always return an empty JSON encoded output
			else {
				return ['output' => '', 'message' => ''];
			}
		}
		
		// Else return to rendering a normal view
		return $this->render('view', ['model' => $model]);
	}
	
	public function actionUpdate($id, $questoinId,$courseMainId)
	{
		$model = new ReplySearch(); // your model can be loaded here
		
		// Check if there is an Editable ajax request
		if (isset($_POST['hasEditable'])) {
			// use Yii's response format to encode output as JSON
			\Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
			
			// read your posted model attributes
			if ($model->load($_POST)) {
				// read or convert your posted information
				$value = $model->replyContent;
				$model->userId = 137;
				$model->courseMainId = $courseMainId;
				if (trim($value) == '') {
					return ['output' => $value, 'message' => '不能为空'];
				} else if (mb_strlen(trim($value)) > 1024) {
					return ['output' => $value, 'message' => '不能超过1024个字符'];
				}
				if ($model->update($id)) {
					// return JSON encoded output in the below format
					return ['output' => $value, 'message' => '', 'id' => $questoinId, 'updateTime' => date('Y-m-d H:i:s', time())];
				} else {
					return ['output' => $value, 'message' => '回复失败'];
				}
				// alternatively you can return a validation error
				// return ['output'=>'', 'message'=>'Validation error'];
			} // else if nothing to do always return an empty JSON encoded output
			else {
				return ['output' => '', 'message' => ''];
			}
		}
		
		// Else return to rendering a normal view
		return $this->render('view', ['model' => $model]);
	}
	
	/**
	 * Deletes an existing Reply model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.
	 * @param integer $id
	 * @return mixed
	 */
	public function actionDelete($id, $courseMainId)
	{
		Yii::info('actionDelete reply id:' . $id);
		$model = new ReplySearch();
		$model->id = $id;
		$model->delete();
		
		return $this->redirect(['reply-index', 'courseMainId' => $courseMainId]);
		
	}
	
	/**
	 * Finds the Reply model based on its primary key value.
	 * If the model is not found, a 404 HTTP exception will be thrown.
	 * @param integer $id
	 * @return Reply the loaded model
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	protected function findModel($id)
	{
		$model = new ReplySearch();
		
		if ($id != null) {
			$rhttp = new RestfulHttp('/reply/' . $id);
			$data = $rhttp->get();
		}
		
		$result = $data['data'];
		
		if ($data['success'] == 'true') {
			$model->load($result, 'result');
			$t = $result['result'];
			$user = new UserSearch();
			$user->load($t, 'user');
			$model->user = $user;
			
			return $model;
		} else {
			return new NotFoundHttpException('The requested page does not exist.');
		}
	}
}

frontend/views/reply/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use frontend\assets\AppAsset;
use yii\widgets\DetailView;


/* @var $this yii\web\View */
/* @var $model app\models\News */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="news-form">

    <?php $form = ActiveForm::begin(); ?>
    
    <?=DetailView::widget ( [ 'model' => $question,'attributes' => [ 
    		[ 'label' => '留言内容','format' => 'html','value' => function ($model) {return base64_decode ( $model ['replyContent'] );} ],
    		[
    				'label'=>'留言时间',
    				'value'=>function($model){
    				return date('Y-m-d H:i:s',$model['createTime']/1000);
    		}
    		],
    		[
    				'label'=>'留言用户',
    				'value'=>function($model){
    				return base64_decode($model['user']['weinickname']);
    		}
    		],
    		[
    				'label'=>'留言状态',
    				'value'=>function($model){
    				if($model['replyStatus'] == '0') {
    					return '未回复';
    				} else {
    					return '已回复';
    				}
    		}
    		],
    		] ] )?>

    <?= $form->field($model, 'replyContent')->textarea(['maxlength' => true]) ?>
    <?= $form->field($model, 'userId')->hiddenInput(['value'=>1])->label(false)?>



    <div class="form-group">
        <?= Html::submitButton('回复', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

	<?php $this->registerJs($this->blocks['javascript-block'], \yii\web\View::POS_END); ?>
</div>

frontend/views/reply/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\date\DatePicker;

/* @var $this yii\web\View */
/* @var $model app\models\ReplySearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="reply-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'id' => 'reply-search',
    		'validateOnChange'=> false,
    		'validateOnSubmit'=>false,
    		'validateOnBlur'=>false,
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>


   <?php
       
		echo '<label>发布时间</label>';
		echo DatePicker::widget([
			'name' => 'CourseMainSearch[publishTimeStart]',
			'value' => $model->publishTimeStart,
			'type' => DatePicker::TYPE_RANGE,
			'name2' => 'CourseMainSearch[publishTimeEnd]',
			'value2' => $model->publishTimeEnd,
		    'pluginOptions' => [
		    		'format' => 'yyyy/mm/dd',
		    		'clearBtn' => true,
		    		'autoclose' => true,
		    		'todayHighlight' => true
		    ]
		]);
	?>


    <?= $form->field($model, 'courseMainName') ?>

    <div class="form-group">
        <?= Html::submitButton('查询', ['class' => 'btn btn-primary']) ?>
        <?= Html::Button('重置', ['class' => 'btn btn-default','onclick'=>'resetSearchForm("reply-search");']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/reply/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Reply */

$this->title = 'Create Reply';
$this->params['breadcrumbs'][] = ['label' => 'Replies', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="reply-create">


    <?= $this->render('_form', [
        'model' => $model,
    		'question' => $question,
    ]) ?>

</div>

frontend/views/reply/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\helpers\Url;
use yii\widgets\LinkPager;

/* @var $this yii\web\View */
/* @var $searchModel app\models\ReplySearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = '留言管理';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="reply-index">
    <?php Pjax::begin(); ?>
    <?php echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
        		['class' => 'yii\grid\SerialColumn','header'=>'序号'],
        		[
        				'header'=>'课程名称',
        				'class' => 'yii\grid\Column',
        				'content' => function($model){
        				return Html::a(Html::encode($model['courseMainName']),Url::to(['/reply/reply-index','courseMainId'=>$model['id']]), ['title'=>$model['courseMainName'],'class'=>'ellipsis','style'=>'width:200px;']);
			    },
			    ],
			    [
			    		'attribute' => '讲师',
			    		'value' => function($model){
			    		return $model['teacher']['teacherName'];
			    },
			    ],
			    [
			    		'attribute' => '留言数量',
			    		'value' => function($model){
			    		return $model['replyCount'];
			    },
			    ],
			    [
			    		'attribute' => '发布时间',
			    		'value' => function($model){
			    		if(!is_null($model['publishTime'])){
			    			return date('Y-m-d H:i:s',$model['publishTime']/1000);
			    		}else{
			    			return '';
			    		}
			    },
			    ],
			    [
			    		'attribute' => '最新留言时间',
			    		'value' => function($model){
			    		if(!is_null($model['replyLatestTime'])){
			    			return date('Y-m-d H:i:s',$model['replyLatestTime']/1000);
			    		}else{
			    			return '';
			    		}
			    },
			    ],
			    [
			    		'class' => 'yii\grid\ActionColumn',
			    		'template' => '{update}',
			    		'buttons' => [
			    				'update' => function ($url, $model, $key) {
			    				if ($model['replyCount'] > 0) {
			    					return Html::a('管理留言', ['reply-index', 'courseMainId' => $model['id']], ['class'=>'btn btn-sm btn-primary']);
			    				}
			    		}
			    		],
			    ],
        ],
    ]); ?>
    <?php 
    	echo LinkPager::widget([
    		'pagination' => $page,
	    ]);
    ?>
    
    <?php Pjax::end(); ?>
</div>

frontend/views/reply/reply_index.php
<?php

use yii\helpers\Html;
use yii\bootstrap\Modal;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\helpers\Url;
use yii\widgets\LinkPager;
use kartik\editable\Editable;

$this->title = '留言回复';
$this->params['breadcrumbs'][] = ['label' => '留言管理', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="reply-index">
    <h1>课程名称：<?= Html::encode($courseMain['courseMainName']) ?></h1>
    <?php echo $this->render('reply_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'options' => [
            'style' => 'overflow: auto; word-wrap: break-word;'
        ],
        'columns' => [
            ['class' => 'yii\grid\SerialColumn', 'header' => '序号'],
            [
                'header' => '留言内容',
                'class' => 'yii\grid\Column',
                'content' => function ($model) {
                	return Html::tag("div", Html::encode(base64_decode($model['replyContent'])), ['title' => base64_decode($model['replyContent']), 'style' => 'width:200px;']);
                },
            ],
            [
                'attribute' => '留言时间',
                'options' => ['width' => '10'],
                'value' => function ($model) {
                    if (!is_null($model['createTime'])) {
                        return date('Y-m-d H:i:s', $model['createTime'] / 1000);
                    } else {
                        return '';
                    }
                },
            ],
            [
                'attribute' => '留言用户',
                'value' => function ($model) {
                    return base64_decode($model['user']['weinickname']);
                },
            ],
            [
                'attribute' => '状态',
                'content' => function ($model) {
                    if ($model['replyStatus'] == '0') {
                        return Html::tag('span', '未回复', ['id' => 'status' . $model['id']]);
                    } else {
                        return Html::tag('span', '已回复', ['id' => 'status' . $model['id']]);
                    }
                },
            ],
            [
                'header' => '回复内容',
                'class' => 'yii\grid\Column',
                'content' => function ($model) {
                    return Editable::widget([
                        'name' => 'ReplySearch[replyContent]',
                        'pluginEvents' => ["editableSuccess" => "addReply"],
                        'ajaxSettings' => ['url' => isset($model['replyList'][0]) ? Url::toRoute(['reply/update', 'id' => $model['replyList'][0]['id'], 'questoinId' => $model['id'],'courseMainId' => $model['courseMainId']]) : Url::toRoute(['reply/create', 'questoinId' => $model['id'],'courseMainId' => $model['courseMainId']])],
                        'asPopover' => true,
                    		'value' => isset($model['replyList'][0]) ? Html::encode(base64_decode($model['replyList'][0]['replyContent'])) : '',
                        'header' => '回复内容',
                        'size' => 'md',
                        'inputType' => Editable::INPUT_TEXTAREA,
                        'editableValueOptions' => ['class' => 'kv-editable-value kv-editable-link ellipsis', 'style' => 'width:100px;'],
                    	'options' => ['class' => 'form-control','maxlength'=>1024]
                    ]);
                },
            ],
            [
                'attribute' => '回复时间',
                'options' => ['width' => '10'],
                'content' => function ($model) {
                    if (isset($model['replyList'][0])) {
                        return Html::tag('span', date('Y-m-d H:i:s', $model['replyList'][0]['updateTime'] / 1000), ['id' => 'updateTime' . $model['id']]);
                    } else {
                        return Html::tag('span', '', ['id' => 'updateTime' . $model['id']]);
                    }
                },
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{delete}',
                'buttons' => [
                    'delete' => function ($url, $model, $key) {
                        return Html::a('删除', ['delete', 'id' => $model['id'], 'courseMainId' => $model['courseMainId']],
                            ['class' => 'btn btn-sm btn-danger', 'data' => [
                                'confirm' => '你确定删除这条留言吗?',
                                'method' => 'post',
                            ],
                            ]);
                    }
                ],
            ]
        ],
    ]); ?>

    <?php
    echo LinkPager::widget([
        'pagination' => $page,
    ]);
    ?>

</div>
<?php $this->beginBlock('javascript-block') ?>
function addReply(event, val, form, data) {
$('#status'+data.id).html('已回复');
$('#updateTime'+data.id).html(data.updateTime);
}
<?php $this->endBlock() ?>
<?php $this->registerJs($this->blocks['javascript-block'], \yii\web\View::POS_END); ?>

frontend/views/reply/reply_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\date\DatePicker;

/* @var $this yii\web\View */
/* @var $model app\models\ReplySearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="reply-index-search">

    <?php $form = ActiveForm::begin([
        'action' => ['reply-index'],
        'method' => 'get',
        'id' => 'reply-index-search',
    		'validateOnChange'=> false,
    		'validateOnSubmit'=>false,
    		'validateOnBlur'=>false,
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>


   <?php
       
		echo '<label>留言发布时间</label>';
		echo DatePicker::widget([
			'name' => 'ReplySearch[createTimeStart]',
			'value' => $model->createTimeStart,
			'type' => DatePicker::TYPE_RANGE,
			'name2' => 'ReplySearch[createTimeEnd]',
			'value2' => $model->createTimeEnd,
		    'pluginOptions' => [
		    		'format' => 'yyyy/mm/dd',
		    		'clearBtn' => true,
		    		'autoclose' => true,
		    		'todayHighlight' => true
		    ]
		]);
	?>
	
	<br>
	
	<?= $form->field($model, 'replyStatus')->dropDownList(array(''=>'所有','0'=>'未回复','1'=>'已回复'))?>



    <div class="form-group">
        <?= Html::submitButton('查询', ['class' => 'btn btn-primary']) ?>
        <?= Html::Button('重置', ['class' => 'btn btn-default','onclick'=>'resetSearchForm("reply-index-search");']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/reply/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Reply */

$this->title = 'Create Reply';
$this->params['breadcrumbs'][] = ['label' => 'Replies', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="reply-update">


    <?= $this->render('_form', [
    		'model' => $model,
    		'question' => $question,
    ]) ?>

</div>