frontend/models/Course.php
<?php

namespace app\models;

use Yii;
use yii\base\Model;
use common\models\CommonModel;

/**
 * This is the model class for table "pgdx_course".
 *
 * @property int $id
 * @property string $courseName 小课名称
 * @property resource $courseContent 文稿
 * @property string $createTime
 * @property string $updateTime
 * @property string $courseStatus 状态 0:未发布  1:已发布 冗余pgdx_course_main的status
 * @property string $publishTime 冗余pgdx_course_main的publishTime
 * @property int $attachId 附件ID
 * @property double $attachSize 附件大小，单位M，冗余pgdx_attach的size
 * @property double $duration 时长(音频、视频播放长度)，冗余pgdx_attach的duration
 * @property int $statisticsId 统计数据ID
 * @property string $type  audio(音频),video(视频)
 * @property int $teacherId 讲师ID,冗余pgdx_course_main的teacherId
 * @property string $tags 标签，多个标签逗号(,)分隔
 * @property string $isdel 是否已删除 0:未删除 1:已删除
 */
class Course extends CommonModel
{
	public $id;
	
	public $courseName;
	
	public $createTime;
	
	public $updateTime;
	
	public $courseStatus;
	
	public $publishTime;
	
	public $attachId;
	
	public $attachSize;
	
	public $duration;
	
	public $statisticsId;
	
	public $courseType;
	
	public $teacherId;
	
	public $tags;
	
	public $isdel;
	
	public $courseOrder;
	
	public $courseContent;
	
	public $courseMainId;
	public $demoFlag;
	public $shareTitle; //
	public $shareSummary; //
	
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'pgdx_course';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['courseName', 'courseContent', 'updateTime', 'courseStatus', 'teacherId', 'courseOrder','shareTitle', 'shareSummary'], 'required'],
            [['courseContent', 'demoFlag'], 'string'],
        	[['createTime', 'updateTime', 'publishTime'], 'safe'],
        	[['id', 'attachId', 'statisticsId', 'teacherId','courseMainId', 'courseOrder'], 'integer'],
            [['attachSize', 'duration'], 'number'],
            [['courseName'], 'string', 'max' => 64],
            [['shareTitle'], 'string', 'max' => 32],
            [['shareSummary'], 'string', 'max' => 64],
            [['courseStatus', 'isdel'], 'string', 'max' => 1],
            [['courseType'], 'string', 'max' => 5],
            [['tags'], 'string', 'max' => 2014],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'courseName' => '小课名称',
            'courseContent' => '文稿',
            'courseOrder' => '小课顺序',
            'createTime' => 'Create Time',
            'updateTime' => 'Update Time',
            'courseStatus' => '状态 0:未发布  1:已发布 冗余pgdx_course_main的status',
            'publishTime' => '冗余pgdx_course_main的publishTime',
            'attachId' => '附件ID',
            'attachSize' => '附件大小，单位M，冗余pgdx_attach的size',
            'duration' => '时长(音频、视频播放长度)，冗余pgdx_attach的duration',
            'statisticsId' => '统计数据ID',
            'type' => ' audio(音频),video(视频)',
            'teacherId' => '讲师ID,冗余pgdx_course_main的teacherId',
            'tags' => '标签，多个标签逗号(,)分隔',
            'isdel' => '是否已删除 0:未删除 1:已删除',
            'demoFlag' => '是否试听',
            'shareTitle' => '转发标题',
            'shareSummary' => '转发摘要',
        ];
    }

    /**
     * @inheritdoc
     * @return CourseQuery the active query used by this AR class.
     */
    public static function find()
    {
        //return new CourseQuery(get_called_class());
    }
}

frontend/controllers/CourseController.php
<?php

namespace frontend\controllers;

use Yii;
use app\models\Course;
use app\models\CourseSearch;
use app\models\AttachSearch;
use app\models\CourseMainSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\NotAcceptableHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\http\RestfulHttp;
use app\models\CourseMain;
use yii\httpclient\Client;
use common\controller\CommonController;
use SebastianBergmann\CodeCoverage\Report\Html\Renderer;


/**
 * CourseController implements the CRUD actions for Course model.
 */
class CourseController extends CommonController
{
	public $enableCsrfValidation = false;
	
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => [],
                        'allow' => true,
                        'roles' => ['@'],
                    ]
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }
    
    public function actions()
    {
    	return [
    			'error' => [
    					'class' => 'yii\web\ErrorAction',
    			],
    			'captcha' => [
    					'class' => 'yii\captcha\CaptchaAction',
    					'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
    			],
    	];
    }
    
    public function actionEditDemo($id,$type,$courseMainId=0) {
    	$model = new CourseSearch(); // your model can be loaded here
    	
    	// Check if there is an Editable ajax request
    	if (isset($_POST['hasEditable'])) {
    		// use Yii's response format to encode output as JSON
    		\Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
    		
    		// read your posted model attributes
    		if ($model->load($_POST)) {
    			// read or convert your posted information
    			$model->id = $id;
    			if ($type == '1') {
    				$value = $model->courseName;
    			} else if ($type == '2') {
    				$value = $model->courseOrder;
    				$model->courseMainId = $courseMainId;
    				if (!$model->checkOrder()) {
    					return ['output'=>$value, 'message'=>'小课顺序已存在'];
    				}
    			} else if ($type == '3') {
    				$value = $model->demoFlag;
    				if ($value == '0') {
    					$value = "否";
    				} 
    				if ($value == '1') {
    					$value = "是";
    				}
    			} else if ($type == '4') {
    				$value = $model->shareTitle;
    			} else if ($type == '5') {
    				$value = $model->shareSummary;
    			}
    			
    			if(trim($value) == '') {
    				return ['output'=>$value, 'message'=>'不能为空'];
    			}
    			
    			if ($model->update()) {
	    			// return JSON encoded output in the below format
	    			return ['output'=>$value, 'message'=>''];
    			} else {
	    			return ['output'=>$value, 'message'=>'更新失败'];
    			}
    			// alternatively you can return a validation error
    			// return ['output'=>'', 'message'=>'Validation error'];
    		}
    		// else if nothing to do always return an empty JSON encoded output
    		else {
    			return ['output'=>'', 'message'=>''];
    		}
    	}
    	
    	// Else return to rendering a normal view
    	return $this->render('view', ['model'=>$model]);
    }
    
    public function actionViewSubs($courseMainId)
    {
    	$searchModel = new CourseSearch();
    	
    	//对应主课程信息
    	$courseMain= CourseMainSearch::findModel($courseMainId);
    	//var_dump($courseMain);
    	
    	//记录主课程ID
    	$model = new CourseSearch();
    	$model->courseMainId = $courseMainId;
    	
    	$courseSearch = new CourseSearch();
    	$dataProvider=$courseSearch->searchByCourseMainId($courseMainId);
    	
    	return $this->render('index', [
    			'model'=> $model,
    			'courseMain' => $courseMain,
    			'searchModel' => $searchModel,
    			'dataProvider' => $dataProvider,
    	]);
    	
    }

    /**
     * Displays a single Course model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Course model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new CourseSearch();
        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
        	Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        	return \yii\widgets\ActiveForm::validate($model);
        }
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
        	return $this->redirect(['view-subs', 'courseMainId' => $model->courseMainId]);
        } else {
        	return $this->redirect(['view-subs', 'courseMainId' => $model->courseMainId]);
        }
    }
    
    public function actionUpdateContent($id){
    	$model = new CourseSearch();
    	$model->id = $id;
    	if ($model->load(Yii::$app->request->post()) && $model->updateContent()) {
    		$model = $this->findModel($id);
    		return $this->redirect(['view-subs', 'courseMainId' => $model->courseMainId]);
    	} else {
    		$model = $this->findModel($id);
    		return $this->render('updatecontent', [
    				'model' => $model,
    		]);
    	}
    }

    /**
     * Updates an existing Course model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }
    
    public function actionUploadAttach(){
    	$model = new CourseSearch();
    	
    	if ($model->load(Yii::$app->request->post()) && $model->uploadAttach()) {
	    	return $this->redirect(['view-subs', 'courseMainId' => $model->courseMainId]);
    	} else {
    		throw new NotAcceptableHttpException();
    	}
    }
    
    public function actionPlayAudio($src){
    	return $this->renderAjax('_play',['src'=>$src]);
    	
    }

    /**
     * Deletes an existing Course model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
    	Yii::info('actionDelete course id:'.$id);
    	$model = new CourseSearch();
    	$model = $this->findModel($id);
    	
    	$courseMainId = $model->courseMainId;
    	Yii::info('actionDelete courseMainId:'.$model->courseMainId);
    	Yii::info('actionDelete course id:'.$model->id);
        
    	$model->delete();

    	return $this->redirect(['view-subs', 'courseMainId' => $courseMainId]);
    }

    /**
     * Finds the Course model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Course the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
    	$model= new CourseSearch();
    	//$teacher= new UserSearch();
    	
    	
    	if($id != null){
    		$rhttp = new RestfulHttp('/course/sub/'.$id);
    		$data = $rhttp->get();
    	}
    	
    	$result = $data['data'];
    	
    	if($data['success']=='true'){
			$attach= new AttachSearch();
			$attach->load($result['result'],'attach');
			$model->load($result,'result');
			$model->attach=$attach;
    		return $model;
    	}else{
    		return new NotFoundHttpException('The requested page does not exist.');;
    	}
    }
}

frontend/views/course/_create.php
<?php
use yii\helpers\Html;

use yii\helpers\Url;
use yii\widgets\ActiveForm;

$this->title = '新增小课';
?>
<?php $form = ActiveForm::begin(['id'=>'course-search','action'=>Url::toRoute(['course/create']),'enableAjaxValidation' => true]) ?>

<?= $form->field($model, 'courseName')->textInput() ?>

<?php if (Yii::$app->session['datasource']== 'app') {
	echo $form->field($model, 'shareTitle')->textInput(['maxlength' => true]);
	echo $form->field($model, 'shareSummary')->textarea(['maxlength' => true]);
}?>


<?= $form->field($model, 'courseOrder')->textInput() ?>

<?php if (Yii::$app->session['datasource']== 'app') {
	echo $form->field($model, 'demoFlag')->dropDownList(array('0'=>'否','1'=>'是'));
}?>

<?= Html::hiddenInput('CourseSearch[courseType]', '1') ?>

<?= Html::hiddenInput('CourseSearch[courseMainId]', $model['courseMainId']) ?>

<?= Html::submitButton('新增小课', ['class' => 'btn btn-success']) ?>

 <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
 
<?php ActiveForm::end() ?>

frontend/views/course/_upload.php
<?php
use yii\widgets\ActiveForm;
use kartik\file\FileInput;
use yii\helpers\Url;

$this->title = '上传音频';
?>

<?php $form_upload = ActiveForm::begin(['action'=>Url::toRoute(['course/upload-attach']),'id'=>'uploadForm']) ?>
<?= $form_upload->field($model, 'attachId')->hiddenInput()->label(false) ?>
<?= $form_upload->field($model, 'id')->hiddenInput()->label(false) ?>
<?= $form_upload->field($model, 'courseMainId')->hiddenInput()->label(false) ?>
<?php 
	echo FileInput::widget([
		'name' => 'uploadfile',
		'options'=>[
				'multiple'=>false,
				'required'=>true,
				'accept' => 'audio/mpeg'
		],
			'pluginOptions' => [
					'allowedFileExtensions'=> ['mp3'],
					'allowedPreviewTypes' => ['audio'],
					'uploadUrl' => Url::toRoute(['course/upload-audio']),
					'maxFileCount' => 1,
					'dropZoneTitle' => '请上传文件',
					'progressUploadThreshold' => '99',
					'maxFileSize'=>71680,
					'fileActionSettings' => ['showRemove'=>false, 'showDrag'=>false,'showUpload'=>false],
			],
			'pluginEvents' => [
					'fileuploaded' => "function(event, data, previewId, index) {
											$('#coursesearch-attachid').val(data.response['id']);
											$('#uploadForm').submit();
		 								}",
			],
	]);
?>
<?php ActiveForm::end() ?>

frontend/views/course/index.php
<?php

use yii\helpers\Html;
use kartik\editable\Editable;
use yii\grid\GridView;
use yii\bootstrap\Modal;
use yii\helpers\Url;
use yii\widgets\DetailView;
use kartik\file\FileInput;

/* @var $this yii\web\View */
/* @var $searchModel app\models\CourseSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = '子课程列表';
$this->params['breadcrumbs'][] = ['label' => '精品课程', 'url' => ['course-main/index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="course-index">
    <?= DetailView::widget([
        'model' => $courseMain,
        'attributes' => [
            'courseMainName',

        ],
    ]) ?>
    <p>
        <?= Html::a('添加小课', ['#'], [
            'id' => 'create',
            'data-toggle' => 'modal',
            'data-target' => '#course-new-modal',
            'class' => 'btn btn-success',
        ]) ?>
    </p>

    <?php if (Yii::$app->session['datasource']== 'app') {
    	echo GridView::widget([
    			'dataProvider' => $dataProvider,
    			'options' => [
    					'style' => 'overflow: auto; word-wrap: break-word;'
    			],
    			//'filterModel' => $searchModel,
    			'columns' => [
    					[
    							'attribute' => '顺序',
    							'content' => function ($model) {
    							return Editable::widget([
    									'name' => 'CourseSearch[courseOrder]',
    									'ajaxSettings' => ['url' => Url::toRoute(['course/edit-demo', 'id' => $model['id'], 'type' => '2', 'courseMainId'=>$model['courseMainId']])],
    									'asPopover' => true,
    									'value' => $model['courseOrder'],
    									'header' => '顺序',
    									'size' => 'md',
    									'options' => ['class' => 'form-control']
    							]);
    					},
    					],
    					[
    							'header' => '小课名称',
    							'class' => 'yii\grid\Column',
    							'content' => function ($model) {
    							return Editable::widget([
    									'name' => 'CourseSearch[courseName]',
    									'ajaxSettings' => ['url' => Url::toRoute(['course/edit-demo', 'id' => $model['id'], 'type' => '1'])],
    									'asPopover' => true,
    									'value' => Html::encode($model['courseName']),
    									'header' => '小课名称',
    									'size' => 'md',
    									'inputType' => Editable::INPUT_TEXTAREA,
    									'editableValueOptions' => ['class' => 'kv-editable-value kv-editable-link ellipsis', 'style' => 'width:100px;'],
    									'options' => ['class' => 'form-control','maxlength'=>64]
    							]);
    					},
    					],
    					[
    							'header' => '转发标题',
    							'class' => 'yii\grid\Column',
    							'content' => function ($model) {
    							return Editable::widget([
    									'name' => 'CourseSearch[shareTitle]',
    									'ajaxSettings' => ['url' => Url::toRoute(['course/edit-demo', 'id' => $model['id'], 'type' => '4'])],
    									'asPopover' => true,
    									'value' => Html::encode($model['shareTitle']),
    									'header' => '转发标题',
    									'size' => 'md',
    									'editableValueOptions' => ['class' => 'kv-editable-value kv-editable-link ellipsis', 'style' => 'width:100px;'],
    									'options' => ['class' => 'form-control','maxlength'=>32]
    							]);
    					},
    					],
    					[
    							'header' => '转发摘要',
    							'class' => 'yii\grid\Column',
    							'content' => function ($model) {
    							return Editable::widget([
    									'name' => 'CourseSearch[shareSummary]',
    									'ajaxSettings' => ['url' => Url::toRoute(['course/edit-demo', 'id' => $model['id'], 'type' => '5'])],
    									'asPopover' => true,
    									'value' => Html::encode($model['shareSummary']),
    									'header' => '转发摘要',
    									'size' => 'md',
    									'inputType' => Editable::INPUT_TEXTAREA,
    									'editableValueOptions' => ['class' => 'kv-editable-value kv-editable-link ellipsis', 'style' => 'width:100px;'],
    									'options' => ['class' => 'form-control','maxlength'=>64]
    							]);
    					},
    					],
    					[
    							'header' => '试听',
    							'options' => ['width' => '1'],
    							'class' => 'yii\grid\Column',
    							'content' => function ($model) {
    							return Editable::widget([
    									'name' => 'CourseSearch[demoFlag]',
    									'ajaxSettings' => ['url' => Url::toRoute(['course/edit-demo', 'id' => $model['id'], 'type' => '3'])],
    									'asPopover' => true,
    									'header' => '试听标志',
    									'value' => $model['demoFlag'] == '0' ? "否" : "是",
    									'inputType' => Editable::INPUT_DROPDOWN_LIST,
    									'data' => array('0' => '否', '1' => '是'), // any list of values
    									'options' => ['class' => 'form-control', 'prompt' => '请选择'],
    							]);
    					},
    					],
    					[
    							'header' => '音频',
    							'class' => 'yii\grid\Column',
    							'content' => function ($model) {
    							if ($model['attachId'] == null) {
    								
    								return Html::a('上传', '#', [
    										'id' => 'upload',
    										'class' => 'upload',
    										'data-toggle' => 'modal',
    										'data-target' => '#upload-modal',
    										'data-id' => $model['id'],
    										'data-courseMainId' => $model['courseMain']['id'],
    								]);
    							} else {
    								return Html::a('试听', '#', [
    										'id' => 'audio',
    										'class' => 'audio',
    										'data-toggle' => 'modal',
    										'data-target' => '#audio-modal',
    										'data-id' => $model['id'],
    										'data-src' => $model['attach']['attachFullPath'],
    										'data-courseMainId' => $model['courseMain']['id'],
    								]) . "  " . Html::a('重新上传', '#', [
    										'id' => 'upload',
    										'class' => 'upload',
    										'data-toggle' => 'modal',
    										'data-target' => '#upload-modal',
    										'data-id' => $model['id'],
    										'data-courseMainId' => $model['courseMain']['id'],
    								]);
    							}
    							
    					},
    					],
    					[
    							'header' => '文稿',
    							'class' => 'yii\grid\Column',
    							'content' => function ($model) {
    							if ($model['courseContent'] == null) {
    								$str = '去添加';
    							} else {
    								$str = '修改';
    							}
    							return Html::a($str, Url::to(['/course/update-content', 'id' => $model['id']]));
    							},
    							],
    							[
    									'attribute' => '发布时间',
    									'options' => ['width' => '10'],
    									'value' => function ($model) {
    									if (!empty($model['courseMain']['publishTime'])) {
    										return date('Y-m-d H:i:s', $model['courseMain']['publishTime'] / 1000);
    									} else {
    										return '';
    									}
    									},
    									],
    									[
    											'class' => 'yii\grid\ActionColumn',
    											'template' => '{view}',
    											'buttons' => [
    													'view' => function ($url, $model, $key) {
    													return Html::a('预览', ['view', 'id' => $model['id']], ['class' => 'btn btn-sm btn-info']);
    											}
    											],
    											'options' => [
    													'width' => 5
    											]
    											],
    											[
    													'class' => 'yii\grid\ActionColumn',
    													'template' => '{delete}',
    													'buttons' => [
    															'delete' => function ($url, $model, $key) {
    															return Html::a('删除', ['delete', 'id' => $model['id']],
    																	['class' => 'btn btn-sm btn-danger', 'data' => [
    																			'confirm' => '你确定删除这条课程信息吗?',
    																			'method' => 'post',
    																	],
    																	]);
    											}
    											],
    											'options' => [
    													'width' => 5
    											]
    											],
    											
    											],
    											]);
    } else {
    	echo GridView::widget([
    			'dataProvider' => $dataProvider,
    			'options' => [
    					'style' => 'overflow: auto; word-wrap: break-word;'
    			],
    			//'filterModel' => $searchModel,
    			'columns' => [
    					[
    							'attribute' => '顺序',
    							'content' => function ($model) {
    							return Editable::widget([
    									'name' => 'CourseSearch[courseOrder]',
    									'ajaxSettings' => ['url' => Url::toRoute(['course/edit-demo', 'id' => $model['id'], 'type' => '2', 'courseMainId'=>$model['courseMainId']])],
    									'asPopover' => true,
    									'value' => $model['courseOrder'],
    									'header' => '小课名称',
    									'size' => 'md',
    									'options' => ['class' => 'form-control']
    							]);
    					},
    					],
    					[
    							'header' => '小课名称',
    							'class' => 'yii\grid\Column',
    							'content' => function ($model) {
    							return Editable::widget([
    									'name' => 'CourseSearch[courseName]',
    									'ajaxSettings' => ['url' => Url::toRoute(['course/edit-demo', 'id' => $model['id'], 'type' => '1'])],
    									'asPopover' => true,
    									'value' => Html::encode($model['courseName']),
    									'header' => '小课名称',
    									'size' => 'md',
    									'inputType' => Editable::INPUT_TEXTAREA,
    									'editableValueOptions' => ['class' => 'kv-editable-value kv-editable-link ellipsis', 'style' => 'width:200px;'],
    									'options' => ['class' => 'form-control','maxlength'=>64]
    							]);
    					},
    					],
    					[
    							'header' => '音频',
    							'class' => 'yii\grid\Column',
    							'content' => function ($model) {
    							if ($model['attachId'] == null) {
    								
    								return Html::a('上传', '#', [
    										'id' => 'upload',
    										'class' => 'upload',
    										'data-toggle' => 'modal',
    										'data-target' => '#upload-modal',
    										'data-id' => $model['id'],
    										'data-courseMainId' => $model['courseMain']['id'],
    								]);
    							} else {
    								return Html::a('试听', '#', [
    										'id' => 'audio',
    										'class' => 'audio',
    										'data-toggle' => 'modal',
    										'data-target' => '#audio-modal',
    										'data-id' => $model['id'],
    										'data-src' => $model['attach']['attachFullPath'],
    										'data-courseMainId' => $model['courseMain']['id'],
    								]) . "  " . Html::a('重新上传', '#', [
    										'id' => 'upload',
    										'class' => 'upload',
    										'data-toggle' => 'modal',
    										'data-target' => '#upload-modal',
    										'data-id' => $model['id'],
    										'data-courseMainId' => $model['courseMain']['id'],
    								]);
    							}
    							
    					},
    					],
    					[
    							'header' => '文稿',
    							'class' => 'yii\grid\Column',
    							'content' => function ($model) {
    							if ($model['courseContent'] == null) {
    								$str = '去添加';
    							} else {
    								$str = '修改';
    							}
    							return Html::a($str, Url::to(['/course/update-content', 'id' => $model['id']]));
    							},
    							],
    							[
    									'attribute' => '发布时间',
    									'options' => ['width' => '10'],
    									'value' => function ($model) {
    									if (!empty($model['courseMain']['publishTime'])) {
    										return date('Y-m-d H:i:s', $model['courseMain']['publishTime'] / 1000);
    									} else {
    										return '';
    									}
    									},
    									],
    									[
    											'class' => 'yii\grid\ActionColumn',
    											'template' => '{view}',
    											'buttons' => [
    													'view' => function ($url, $model, $key) {
    													return Html::a('预览', ['view', 'id' => $model['id']], ['class' => 'btn btn-sm btn-info']);
    											}
    											],
    											'options' => [
    													'width' => 5
    											]
    											],
    											[
    													'class' => 'yii\grid\ActionColumn',
    													'template' => '{delete}',
    													'buttons' => [
    															'delete' => function ($url, $model, $key) {
    															return Html::a('删除', ['delete', 'id' => $model['id']],
    																	['class' => 'btn btn-sm btn-danger', 'data' => [
    																			'confirm' => '你确定删除这条课程信息吗?',
    																			'method' => 'post',
    																	],
    																	]);
    											}
    											],
    											'options' => [
    													'width' => 5
    											]
    											],
    											
    											],
    											]);
    }?>

    <?php
    Modal::begin([
        'id' => 'course-new-modal',
        'header' => '<h4 class="modal-title">新增小课</h4>',

    ]);

    echo $this->render('_create', ['model' => $model]);

    Modal::end();
    ?>
    <?php
    Modal::begin([
        'id' => 'upload-modal',
        'header' => '<h4 class="modal-title">上传音频</h4>',
    ]);
	    echo $this->render('_upload', ['model'=>$model]);
    Modal::end();
    ?>
    <?php
    Modal::begin([
        'id' => 'audio-modal',
        'header' => '<h4 class="modal-title">音频试听</h4>',
    ]);



    Modal::end();
    ?>
</div>
<?php $this->beginBlock('javascript-block') ?>
        $(function () {
        	//上传音频
        	$('.upload').on('click',function(){
        		$('#coursesearch-id').val($(this).data('id'));
            });
            //试听音频
            $('.audio').on('click',function(){
            	$.get('<?=Url::toRoute('course/play-audio') ?>', { src: $(this).data('src') },
		            function (data) {
		                $('#audio-modal').find('.modal-body').html(data);
		            }  
        		);
            });
        });
<?php $this->endBlock() ?>
<?php $this->registerJs($this->blocks['javascript-block'], \yii\web\View::POS_END); ?>
	

frontend/views/course/updatecontent.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Course */

$this->title = '修改文稿';
$this->params['breadcrumbs'][] = ['label' => '子课程列表', 'url' => ['course/view-subs','courseMainId'=>$model->courseMainId]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="course-create">
    <?= $this->render('_form', [
        'model' => $model,
        'type' => 'updatecontent',
    ]) ?>

</div>