frontend/models/Promotion.php
<?php

namespace app\models;

use common\models\CommonModel;

class Promotion extends CommonModel
{
	public $id;
	public $icon;
	public $iconId;
	public $refId;
	public $refType;
	public $refName;
	public $refUrl;
	public $createTime;
	public $updateTime;
	public $urlFlag;
	
	/**
	 * @inheritdoc
	 */
	public static function tableName()
	{
		return 'pgdx_promotion';
	}
	
	/**
	 * @inheritdoc
	 */
	public function rules()
	{
		return [
				[['refName', 'refUrl', 'iconId'], 'required'],
				[['id', 'createTime', 'updateTime', 'iconId', 'refId', 'refUrl', 'refType'], 'safe'],
				['refUrl', 'url', 'defaultScheme' => 'http']
		];
	}
	
	/**
	 * @inheritdoc
	 */
	public function attributeLabels()
	{
		return [
				'id' => 'ID',
				'refName' => '落地页',
				'refUrl' => '自定义链接',
				'iconId' => '推广icon',
				'refType' => '推广类型',
		];
	}
}

frontend/controllers/PromotionController.php
<?php

namespace frontend\controllers;

use app\models\Promotion;
use app\models\PromotionSearch;
use app\models\CourseMainSearch;
use app\models\MeetingSearch;
use app\models\ArticleSearch;
use common\page\Page;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

/**
 * PromotionController implements the CRUD actions for Promotion model.
 */
class PromotionController extends Controller
{
	/**
	 * @inheritdoc
	 */
	public function behaviors()
	{
		return [
				'access' => [
						'class' => AccessControl::className(),
						'rules' => [
								[
										'actions' => [],
										'allow' => true,
										'roles' => ['@'],
								]
						],
				],
				'verbs' => [
						'class' => VerbFilter::className(),
						'actions' => [
								'delete' => ['POST'],
						],
				],
		];
	}
	
	/**
	 * Displays a single Promotion model.
	 * @param integer $id
	 * @return mixed
	 */
	public function actionView()
	{
		return $this->render('view', [
				'model' => $this->findModel(1),
		]);
	}
	
	
	/**
	 * Updates an existing Promotion model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id
	 * @return mixed
	 */
	public function actionUpdate()
	{
		$model = new PromotionSearch();
		$model->id = 1;
		if ($model->load(Yii::$app->request->post()) && $model->update()) {
			return $this->redirect(['view', 'id' => $model->id]);
		} else {
			$model = $this->findModel(1);
			return $this->render('update', [
					'model' => $model,
			]);
		}
	}
	
	/**
	 * Finds the Promotion model based on its primary key value.
	 * If the model is not found, a 404 HTTP exception will be thrown.
	 * @param integer $id
	 * @return Promotion the loaded model
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	protected function findModel($id)
	{
		if (($model = PromotionSearch::findModel($id)) !== null) {
			return $model;
		} else {
			throw new NotFoundHttpException('The requested page does not exist.');
		}
	}
	
	public function actionCourseIndex()
	{
		$req_params = Yii::$app->request->queryParams;
		
		//分页
		$page = Page::generatePage($req_params);
		
		//查询主课程信息
		$courseSearch = new CourseMainSearch();
		$dataProvider = $courseSearch->search($req_params, $page);
		
		$searchModel = new CourseMainSearch();
		$searchModel->load($req_params, 'CourseMainSearch');
		
		return $this->renderAjax('course_index', [
				'searchModel' => $searchModel,
				'dataProvider' => $dataProvider,
				'page' => $page,
		]);
	}
	
	public function actionNewsIndex()
	{
		$req_params = Yii::$app->request->queryParams;
		
		//分页
		$page = Page::generatePage($req_params);
		
		//查询主课程信息
		$ArticleSearch = new ArticleSearch();
		$dataProvider = $ArticleSearch->search($req_params, $page);
		
		$categoryList = $ArticleSearch->searchCategory();
		
		$searchModel = new ArticleSearch();
		$searchModel->load($req_params, 'ArticleSearch');
		
		return $this->renderAjax('article_index', [
				'searchModel' => $searchModel,
				'dataProvider' => $dataProvider,
				'categoryList' => $categoryList,
				'page' => $page,
		]);
	}
	
	public function actionMeetingIndex()
	{
		$req_params = Yii::$app->request->queryParams;
		
		//分页
		$page = Page::generatePage($req_params);
		
		//查询主课程信息
		$MeetingSearch = new MeetingSearch();
		$dataProvider = $MeetingSearch->search($req_params, $page);
		
		$searchModel = new MeetingSearch();
		$searchModel->load($req_params, 'MeetingSearch');
		
		return $this->renderAjax('meeting_index', [
				'searchModel' => $searchModel,
				'dataProvider' => $dataProvider,
				'page' => $page,
		]);
	}
}

frontend/views/promotion/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\file\FileInput;
use yii\helpers\Url;
use yii\bootstrap\Modal;

?>

<div class="promotion-form">

    <?php $form = ActiveForm::begin(['validateOnBlur'=>false,'validateOnChange'=>false,]); ?>

    <?= $form->field($model, 'iconId')->hiddenInput()->hint("50px * 50px") ?>
    
    <?php
    echo FileInput::widget([
    		'name' => 'uploadfile',
    		'options'=>[
    				'multiple'=>false,
    				'accept' => 'image/*'
    		],
    		'pluginOptions' => [
    				'showClose' => false,
    				'initialPreview'=>[
    						isset($model->icon) ? $model->icon->attachFullPath : null
    				],
    				'initialPreviewAsData'=>true,
    				'initialPreviewShowDelete'=>false,
    				'initialCaption'=> isset($model->icon) ? $model->icon->orgFileName : null,
    				'initialPreviewConfig' => [
    						['caption' => isset($model->icon) ? $model->icon->orgFileName : null, 'size' => isset($model->icon) ? $model->icon->attachSize * 1024 *1024 : null],
    				],
    				'uploadUrl' => Url::toRoute(['course-main/upload']),
    				'maxFileCount' => 1,//设置ajax上传文件是，一次最多可以上传的文件数量
    				'dropZoneTitle' => '请上传图片',
    				'allowedFileExtensions'=> ['jpg','jpeg','png','bmp','ico'],
    				'fileActionSettings' => ['showRemove'=>false, 'showDrag'=>false,'showUpload'=>false],
    		],
    		'pluginEvents' => [
    				'fileuploaded' => "function(event, data, previewId, index) {
											$('#promotionsearch-iconid').val(data.response['id']);
		 								}",
    				'fileremoved' => "function(event, data, previewId, index) {
											$('#promotionsearch-iconid').val('');
		 								}",
    				'change' => "function(event, data, previewId, index) {
											$('#promotionsearch-iconid').val('');
		 								}",
    		],
    ]);
    ?>
    <br>

    <div class="form-group">
        <?= Html::button('文章库', ['onclick' => 'showArticle();', 'class' => 'btn btn-default test']) ?>
        <?= Html::button('课程库', ['onclick' => 'showCourse();', 'class' => 'btn btn-default test']) ?>
        <?= Html::button('会议库', ['onclick' => 'showMeeting();', 'class' => 'btn btn-default test']) ?>
    </div>

    <?= $form->field($model, 'refId')->hiddenInput()->label(false) ?>
    <?= $form->field($model, 'refType')->hiddenInput()->label(false) ?>

    <?= $form->field($model, 'refName')->textInput() ?>

    <?= Html::checkbox("seflUrl", $model->urlFlag,['id'=>'seflUrl','onclick'=>"clickCheckBox(this);"]) ?>
    
    <?= Html::label("自定义链接","promotionsearch-refurl") ?>
    
    <?= $form->field($model, 'refUrl')->textInput(['disabled' => true])->label(false) ?>

    <div class="form-group">
        <?= Html::submitButton('保存', ['class' => 'btn btn-success']) ?>
        <?= Html::a('返回', Url::to(['/promotion/view']), ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>
</div>

<?php
Modal::begin([
    'id' => 'article-modal',
    'header' => '<h4 class="modal-title">文章库</h4>',
    'size' => 'modal-lg',
]);

Modal::end();
?>
<?php
Modal::begin([
    'id' => 'course-modal',
    'header' => '<h4 class="modal-title">课程库</h4>',
    'size' => 'modal-lg',
]);

Modal::end();
?>
<?php
Modal::begin([
    'id' => 'meeting-modal',
    'header' => '<h4 class="modal-title">会议库</h4>',
    'size' => 'modal-lg',
]);

Modal::end();
?>

<?php $this->beginBlock('javascript-block') ?>
function clickCheckBox(obj) {
	$('.has-error').removeClass('has-error');
	$('.help-block').html('');
	$('#promotionsearch-reftype').val('self');
	if ($(obj).prop('checked') === true) {
		$('#promotionsearch-refname').attr('disabled', true);
		$('#promotionsearch-refname').val('');
		$('#promotionsearch-refid').val('');
		$('#promotionsearch-refurl').removeAttr("disabled");
		$('.test').attr('disabled', true);
	} else {
		$('#promotionsearch-refurl').attr('disabled', true);
		$('#promotionsearch-refurl').val('');
		$('#promotionsearch-refname').removeAttr("disabled");
		$('.test').removeAttr("disabled");
	}
}
function showArticle() {
    $.get('<?= Url::toRoute('promotion/news-index') ?>', {},
        function (data) {
            $('#article-modal').find('.modal-body').html(data);
            $('#article-modal').modal('show');
        }
	);
    $('.field-promotionsearch-refname').show();
    $('#promotionsearch-refurl').val('');

    $('#promotionsearch-refurl').attr('disabled', true);
    $('#promotionsearch-refname').removeAttr("disabled");
}

function showCourse() {
    $.get('<?= Url::toRoute('promotion/course-index') ?>', {},
        function (data) {
            $('#course-modal').find('.modal-body').html(data);
            $('#course-modal').modal('show');
        }
	);
    $('.field-promotionsearch-refname').show();
    $('#promotionsearch-refurl').val('');

    $('#promotionsearch-refurl').attr('disabled', true);
    $('#promotionsearch-refname').removeAttr("disabled");
}

function showMeeting() {
    $.get('<?= Url::toRoute('promotion/meeting-index') ?>', {},
        function (data) {
            $('#meeting-modal').find('.modal-body').html(data);
            $('#meeting-modal').modal('show');
        }
	);
    $('.field-promotionsearch-refname').show();
    $('#promotionsearch-refurl').val('');

    $('#promotionsearch-refurl').attr('disabled', true);
    $('#promotionsearch-refname').removeAttr("disabled");
}
$(function () {
	if ('<?= $model->urlFlag?>' == '1') {
		$('#promotionsearch-refname').attr('disabled', true);
		$('#promotionsearch-refurl').removeAttr("disabled");
		$('.test').attr('disabled', true);
	}
});
<?php $this->endBlock() ?>
<?php $this->registerJs($this->blocks['javascript-block'], \yii\web\View::POS_END); ?>

frontend/views/promotion/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\NewsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="news-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    		'validateOnChange'=> false,
    		'validateOnSubmit'=>false,
    		'validateOnBlur'=>false,
    ]); ?>

    <?= $form->field($model, 'newsTitle') ?>

    <div class="form-group">
        <?= Html::submitButton('查询', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('重置', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/promotion/article_index.php
<?php

use yii\helpers\Html;
use yii\bootstrap\Modal;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\widgets\LinkPager;

/* @var $this yii\web\View */
/* @var $searchModel app\models\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = '实名认证';
$this->params['breadcrumbs'][] = $this->title;
?>
    <div class="article-index-message">

        <?php Pjax::begin(); ?>
        <?php echo $this->render('article_search', ['model' => $searchModel, 'categoryList' => $categoryList]); ?>
        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'columns' => [
                ['header' => '选择',
                    'class' => 'yii\grid\RadioButtonColumn',
                    'headerOptions' => ['width' => '8%'],
                    'radioOptions' => function ($model) {
                        return [
                            'value' => $model['article_id'],
                            'class' => 'testradio',
                        ];
                    }
                ],
                [
                    'attribute' => '文章标题',
                    'value' => function ($model) {
                        return $model['title'];
                    },
                ],
                [
                    'attribute' => '发布时间',
                    'value' => function ($model) {
                        if (!is_null($model['pubtime'])) {
                            return date('Y-m-d H:i:s', $model['pubtime']);
                        } else {
                            return '';
                        }
                    },
                ],
            ],
        ]); ?>
        <?php
        echo LinkPager::widget([
            'pagination' => $page,
        ]);
        ?>
        <?php Pjax::end(); ?>
    </div>
<?php $this->beginBlock('javascript-block') ?>
$(function () {
    $('.testradio').on('click',function(){
        $('#promotionsearch-refname').val($(this).parent().next().html());
        $('#promotionsearch-refid').val($(this).val());
        $('#promotionsearch-reftype').val("article");
        $('#article-modal').modal('hide');
    });
    $('.pagination').find('a').on('click',function(){
        var href = $(this).attr("test");
        console.log(href);
        $.get(href, {},
            function (data) {
                $('#article-modal').find('.modal-body').html(data);
            }
        );
    });
    $('.pagination').find('a').each(function(){
        $(this).attr("test",$(this).attr("href"));
        $(this).attr("href","javascript:void(0);");
    })
});
<?php $this->endBlock() ?>
<?php $this->registerJs($this->blocks['javascript-block'], \yii\web\View::POS_END); ?>

frontend/views/promotion/article_search.php
<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use kartik\date\DatePicker;

/* @var $this yii\web\View */
/* @var $model app\models\NewsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="article-search-promotion">

    <?php $form = ActiveForm::begin(['id'=>'article-search-promotion',
        'action' => ['promotion/news-index'],
        'method' => 'get',
    		'validateOnChange'=> false,
    		'validateOnSubmit'=>false,
    		'validateOnBlur'=>false,
    ]); ?>

	<?php
       
		echo '<label>发布时间</label>';
		echo DatePicker::widget([
			'id' => 'publishDate',
			'name' => 'ArticleSearch[pubtimeStart]',
				'value' => $model->pubtimeStart,
			'type' => DatePicker::TYPE_RANGE,
			'name2' => 'ArticleSearch[pubtimeEnd]',
				'value2' => $model->pubtimeEnd,
		    'pluginOptions' => [
		    		'format' => 'yyyy/mm/dd',
		    		'clearBtn' => true,
		    		'autoclose' => true,
		    		'todayHighlight' => true
		    ]
		]);
	?>
    <?= $form->field($model, 'title') ?>
    
    <?= $form->field($model, 'cid')->dropDownList(ArrayHelper::map($categoryList,'id','name'))?>

    <div class="form-group">
        <?= Html::button('查询', ['id'=>'searchBtn','class' => 'btn btn-primary']) ?>
        <?= Html::Button('重置', ['class' => 'btn btn-default','onclick'=>'resetSearchForm("article-search-promotion");']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

<?php $this->beginBlock('javascript-block') ?>
        $(function () {
        	$('#searchBtn').on('click',function(){
            	$.get('<?=Url::toRoute('promotion/news-index') ?>', $("#article-search-promotion").serialize(),
		            function (data) {
		                $('#article-modal').find('.modal-body').html(data);
		            }  
        		);
            });
        });
<?php $this->endBlock() ?>
<?php $this->registerJs($this->blocks['javascript-block'], \yii\web\View::POS_END); ?>

frontend/views/promotion/course_index.php
<?php

use yii\helpers\Html;
use yii\bootstrap\Modal;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\widgets\LinkPager;

/* @var $this yii\web\View */
/* @var $searchModel app\models\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = '实名认证';
$this->params['breadcrumbs'][] = $this->title;
?>
    <div class="course-index-promotion">

        <?php Pjax::begin(); ?>
        <?php echo $this->render('course_search', ['model' => $searchModel]); ?>
        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'columns' => [
                ['header' => '选择',
                    'class' => 'yii\grid\RadioButtonColumn',
                    'radioOptions' => function ($model) {
                        return [
                            'value' => $model['id'],
                            'class' => 'testradio',
                        ];
                    }
                ],
                [
                    'attribute' => '文章标题',
                    'value' => function ($model) {
                        return $model['courseMainName'];
                    },
                ],
                [
                    'attribute' => '发布时间',
                    'value' => function ($model) {
                        if (!is_null($model['publishTime'])) {
                            return date('Y-m-d H:i:s', $model['publishTime'] / 1000);
                        } else {
                            return '';
                        }
                    },
                ],
            ],
        ]); ?>
        <?php
        echo LinkPager::widget([
            'pagination' => $page,
        ]);
        ?>
        <?php Pjax::end(); ?>
    </div>
<?php $this->beginBlock('javascript-block') ?>
    $(function () {
        $('.testradio').on('click',function(){
        $('#promotionsearch-refname').val($(this).parent().next().html());
        $('#promotionsearch-refid').val($(this).val());
        $('#promotionsearch-reftype').val("course");
        $('#course-modal').modal('hide');
    });
    $('.pagination').find('a').on('click',function(){
    var href = $(this).attr("test");
    console.log(href);
    $.get(href, {},
    function (data) {
    $('#course-modal').find('.modal-body').html(data);
    }
    );
    });
    $('.pagination').find('a').each(function(){
    $(this).attr("test",$(this).attr("href"));
    $(this).attr("href","javascript:void(0);");
    })
    });
<?php $this->endBlock() ?>
<?php $this->registerJs($this->blocks['javascript-block'], \yii\web\View::POS_END); ?>

frontend/views/promotion/course_search.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use kartik\date\DatePicker;

/* @var $this yii\web\View */
/* @var $model app\models\NewsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="course-search-promotion">

    <?php $form = ActiveForm::begin(['id'=>'course-search-promotion',
        'action' => ['promotion/course-index'],
        'method' => 'get',
    		'validateOnChange'=> false,
    		'validateOnSubmit'=>false,
    		'validateOnBlur'=>false,
    ]); ?>

	<?php
       
		echo '<label>发布时间</label>';
		echo DatePicker::widget([
			'id' => 'publishDate',
			'name' => 'CourseMainSearch[publishTimeStart]',
			'value' => $model->publishTimeStart,
			'type' => DatePicker::TYPE_RANGE,
			'name2' => 'CourseMainSearch[publishTimeEnd]',
			'value2' => $model->publishTimeEnd,
		    'pluginOptions' => [
		    		'format' => 'yyyy/mm/dd',
		    		'clearBtn' => true,
		    		'autoclose' => true,
		    		'todayHighlight' => true
		    ]
		]);
	?>
    <?= $form->field($model, 'courseMainName') ?>

    <div class="form-group">
        <?= Html::button('查询', ['id'=>'searchBtn','class' => 'btn btn-primary']) ?>
        <?= Html::Button('重置', ['class' => 'btn btn-default','onclick'=>'resetSearchForm("course-search-promotion");']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

<?php $this->beginBlock('javascript-block') ?>
        $(function () {
        	$('#searchBtn').on('click',function(){
            	$.get('<?=Url::toRoute('promotion/course-index') ?>', $("#course-search-promotion").serialize(),
		            function (data) {
		                $('#course-modal').find('.modal-body').html(data);
		            }  
        		);
            });
        });
<?php $this->endBlock() ?>
<?php $this->registerJs($this->blocks['javascript-block'], \yii\web\View::POS_END); ?>

frontend/views/promotion/meeting_index.php
<?php

use yii\helpers\Html;
use yii\bootstrap\Modal;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\widgets\LinkPager;
?>
<div class="meeting-index-promotion">

    <?php Pjax::begin(); ?>
    <?php echo $this->render('meeting_search', ['model' => $searchModel]); ?>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['header' => '选择',
                'class' => 'yii\grid\RadioButtonColumn',
                'headerOptions' => ['width' => '8%'],
                'radioOptions' => function ($model) {
                    return [
                        'value' => $model['id'],
                        'class' => 'testradio',
                    ];
                }
            ],
            [
                'attribute' => '会议标题',
                'value' => function ($model) {
                    return $model['name'];
                },
            ],
            [
                'attribute' => '开始时间',
                'value' => function ($model) {
                    if (!is_null($model['startTime'])) {
                        return date('Y-m-d H:i:s', $model['startTime']);
                    } else {
                        return '';
                    }
                },
            ],
        ],
    ]); ?>
    <?php
    echo LinkPager::widget([
        'pagination' => $page,
    ]);
    ?>
    <?php Pjax::end(); ?>
</div>
<?php $this->beginBlock('javascript-block') ?>
        $(function () {
            $('.testradio').on('click',function(){
            	$('#promotionsearch-refname').val($(this).parent().next().html());
            	$('#promotionsearch-refid').val($(this).val());
            	$('#promotionsearch-reftype').val("meeting");
            	$('#meeting-modal').modal('hide');
            });
            $('.pagination').find('a').on('click',function(){
            	var href = $(this).attr("test");
            	$.get(href, {},
		            function (data) {
		                $('#meeting-modal').find('.modal-body').html(data);
		            }  
        		);
            });
            $('.pagination').find('a').each(function(){
            	$(this).attr("test",$(this).attr("href"));
            	$(this).attr("href","javascript:void(0);");
            })
        });
<?php $this->endBlock() ?>
<?php $this->registerJs($this->blocks['javascript-block'], \yii\web\View::POS_END); ?>

frontend/views/promotion/meeting_search.php
<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use kartik\date\DatePicker;

/* @var $this yii\web\View */
/* @var $model app\models\NewsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="meeting-search-promotion">

    <?php $form = ActiveForm::begin(['id'=>'meeting-search-promotion',
        'action' => ['promotion/meeting-index'],
        'method' => 'get',
    		'validateOnChange'=> false,
    		'validateOnSubmit'=>false,
    		'validateOnBlur'=>false,
    ]); ?>

	<?php
       
		echo '<label>开始时间</label>';
		echo DatePicker::widget([
			'id' => 'publishDate',
			'name' => 'MeetingSearch[startTimeStart]',
				'value' => $model->startTimeStart,
			'type' => DatePicker::TYPE_RANGE,
			'name2' => 'MeetingSearch[startTimeEnd]',
				'value2' => $model->startTimeEnd,
		    'pluginOptions' => [
		    		'format' => 'yyyy/mm/dd',
		    		'clearBtn' => true,
		    		'autoclose' => true,
		    		'todayHighlight' => true
		    ]
		]);
	?>
    <?= $form->field($model, 'name') ?>
    

    <div class="form-group">
        <?= Html::button('查询', ['id'=>'searchBtn','class' => 'btn btn-primary']) ?>
        <?= Html::Button('重置', ['class' => 'btn btn-default','onclick'=>'resetSearchForm("meeting-search-promotion");']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

<?php $this->beginBlock('javascript-block') ?>
        $(function () {
        	$('#searchBtn').on('click',function(){
            	$.get('<?=Url::toRoute('message/nmeeting-index') ?>', $("#meeting-search-promotion").serialize(),
		            function (data) {
		                $('#meeting-modal').find('.modal-body').html(data);
		            }  
        		);
            });
        });
<?php $this->endBlock() ?>
<?php $this->registerJs($this->blocks['javascript-block'], \yii\web\View::POS_END); ?>

frontend/views/promotion/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\News */

$this->title = '修改APP推广位';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="promotion-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/promotion/view.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;

$this->title = "APP推广位";
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="promotion-view">

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
        	[
        		'label'=>'推广icon',
        		'format'=>'html',
        		'value'=>function($model){
        			if(isset($model['icon'])) {
        				return Html::img($model->icon->attachFullPath,['style'=>'heigth:50px;width:50px;']);
        			}
		    	}
		    ],
		    'refName',
		    'refUrl',
        ],
    ]) ?>
    <p>
        <?= Html::a('修改', Url::to(['/promotion/update']), ['class' => 'btn btn-primary']) ?>
    </p>
</div>